// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeV0UBT98Q_2XT9H_XLhNV7bG72kJnq4',
    appId: '1:294305445462:web:fafc6a1df04bdc7b38adf7',
    messagingSenderId: '294305445462',
    projectId: 'rsi-vgs',
    authDomain: 'rsi-vgs.firebaseapp.com',
    databaseURL: 'https://rsi-vgs.firebaseio.com',
    storageBucket: 'rsi-vgs.appspot.com',
    measurementId: 'G-J8ZDDB5LGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZyW8b--p99F6l5XXs258zURvKsUwcXI',
    appId: '1:294305445462:android:19730fbe724c9a2438adf7',
    messagingSenderId: '294305445462',
    projectId: 'rsi-vgs',
    databaseURL: 'https://rsi-vgs.firebaseio.com',
    storageBucket: 'rsi-vgs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp4YXS3nCM6i3iiWfT6MbVV5pQjmBZTS4',
    appId: '1:294305445462:ios:c74af191e1a80cda38adf7',
    messagingSenderId: '294305445462',
    projectId: 'rsi-vgs',
    databaseURL: 'https://rsi-vgs.firebaseio.com',
    storageBucket: 'rsi-vgs.appspot.com',
    iosBundleId: 'com.example.rsiVgs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp4YXS3nCM6i3iiWfT6MbVV5pQjmBZTS4',
    appId: '1:294305445462:ios:4e3e6c6fb0f11d8e38adf7',
    messagingSenderId: '294305445462',
    projectId: 'rsi-vgs',
    databaseURL: 'https://rsi-vgs.firebaseio.com',
    storageBucket: 'rsi-vgs.appspot.com',
    iosBundleId: 'com.example.rsiVgs.RunnerTests',
  );
}
